"""Change UserReadingProgress unlocked_pages to JSON

Revision ID: 59d42325e06a
Revises: 9279c878dda8
Create Date: 2025-04-07 19:13:16.335840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '59d42325e06a'
down_revision = '9279c878dda8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_reading_progress', schema=None) as batch_op:
        batch_op.alter_column('unlocked_pages',
               existing_type=sa.BLOB(),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.create_unique_constraint('_user_activity_uc', ['user_id', 'activity_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_reading_progress', schema=None) as batch_op:
        batch_op.drop_constraint('_user_activity_uc', type_='unique')
        batch_op.alter_column('unlocked_pages',
               existing_type=sqlite.JSON(),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
