"""Added reading

Revision ID: 9279c878dda8
Revises: 8cf2bab72637
Create Date: 2024-10-25 08:18:23.367028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9279c878dda8'
down_revision = '8cf2bab72637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['reading_activity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_reading_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_pages', sa.PickleType(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['reading_activity.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_reading_progress')
    op.drop_table('reading_page')
    op.drop_table('reading_activity')
    # ### end Alembic commands ###
